name = "SymbolicPolyChaos"
uuid = "5bebe395-998c-492f-8aba-576811a0ac94"
version = "1.0.0-DEV"
authors = ["Jacob Sass <80420670+sass-jacob@users.noreply.github.com> and contributors"]

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Symbolics = "7.5.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
